package MuseumGuard;


/**
* MuseumGuard/GuardPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Domingo, 7 de Outubro de 2018 05h11min28s BRT
*/

public abstract class GuardPOA extends org.omg.PortableServer.Servant
 implements MuseumGuard.GuardOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("changeDayPeriod", new java.lang.Integer (0));
    _methods.put ("getAmountVisitor", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MuseumGuard/Guard/changeDayPeriod
       {
         boolean day = in.read_boolean ();
         boolean $result = false;
         $result = this.changeDayPeriod (day);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // MuseumGuard/Guard/getAmountVisitor
       {
         int visitor = in.read_ulong ();
         int $result = (int)0;
         $result = this.getAmountVisitor (visitor);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MuseumGuard/Guard:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Guard _this() 
  {
    return GuardHelper.narrow(
    super._this_object());
  }

  public Guard _this(org.omg.CORBA.ORB orb) 
  {
    return GuardHelper.narrow(
    super._this_object(orb));
  }


} // class GuardPOA
