package MuseumGuard;


/**
* MuseumGuard/GuardOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Domingo, 7 de Outubro de 2018 05h11min28s BRT
*/

public interface GuardOperations 
{
  boolean changeDayPeriod (boolean day);
  int getAmountVisitor (int visitor);
} // interface GuardOperations
