package MuseumBell;


/**
* MuseumBell/_BellStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 10 de Outubro de 2018 15h55min29s BRT
*/

public class _BellStub extends org.omg.CORBA.portable.ObjectImpl implements MuseumBell.Bell
{

  public boolean ringBell (boolean day, int visitor)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ringBell", true);
                $out.write_boolean (day);
                $out.write_ulong (visitor);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ringBell (day, visitor        );
            } finally {
                _releaseReply ($in);
            }
  } // ringBell

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MuseumBell/Bell:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BellStub
