package MuseumBell;

/**
* MuseumBell/BellHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 10 de Outubro de 2018 15h55min29s BRT
*/

public final class BellHolder implements org.omg.CORBA.portable.Streamable
{
  public MuseumBell.Bell value = null;

  public BellHolder ()
  {
  }

  public BellHolder (MuseumBell.Bell initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MuseumBell.BellHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MuseumBell.BellHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MuseumBell.BellHelper.type ();
  }

}
