package MuseumBell;


/**
* MuseumBell/BellOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Quarta-feira, 10 de Outubro de 2018 15h55min29s BRT
*/

public interface BellOperations 
{
  boolean ringBell (boolean day, int visitor);
} // interface BellOperations
