package MuseumGate;


/**
* MuseumGate/GateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 10 de Outubro de 2018 09h08min36s BRT
*/

public interface GateOperations 
{
  void insertPerson (int person);
  void removePerson (int person);
  int updatePeople ();
} // interface GateOperations
