package MuseumGate;


/**
* MuseumGate/Gate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Portao.idl
* Quarta-feira, 10 de Outubro de 2018 09h08min36s BRT
*/

public interface Gate extends GateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Gate
